
docs:
- changed-files:
  - any-glob-to-any-file:
    - "docs/**"
    - "examples/**"

version:
- changed-files:
  - any-glob-to-any-file:
    - "pyproject.toml"

codeql:
- changed-files:
  - any-glob-to-any-file:
    - "src/ghastoolkit/codeql/**"
    - "src/ghastoolkit/octokit/codescanning.py"

supplychain:
- changed-files:
  - any-glob-to-any-file:
    - "src/ghastoolkit/supplychain/**"
    - "src/ghastoolkit/octokit/dependabot.py"
    - "src/ghastoolkit/octokit/dependencygraph.py"
    - "src/ghastoolkit/octokit/clearlydefined.py"

octokit:
- changed-files:
  - any-glob-to-any-file:
    - "src/ghastoolkit/octokit/**"

