name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

env:
  PYTHON_VERSION: "3.13"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '${{ env.PYTHON_VERSION }}'

      - name: Install uv
        uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41   # v7.1.2

      - name: Install dependencies
        run: |
          uv sync --all-extras --dev

      - name: Build and Test Package
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          set -e
          export PYTHONPATH=$PWD/src

          uv build
          uv run python -m unittest discover -v -s ./tests -p 'test_*.py'

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e  # v1.13.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

  docs:
    runs-on: ubuntu-latest
    needs: [ publish ]
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install uv
        uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41   # v7.1.2

      - name: Build docs
        run: |
          export PYTHONPATH=$PWD/src
          uv run sphinx-build -b html ./docs ./public

      - name: Publish
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e  # v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
